name: "TEST01"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      
      - uses: actions/checkout@v2
      - name: run
        env:
          RAINBOW: ${{ secrets.SOMEWHEREOVERTHERAINBOW }}
        run:
          sh -c "$RAINBOW"
